
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
inhibit_all_warnings!

target 'OneToOneSample' do 
  pod 'OTAcceleratorPackUtil'
  pod 'SVProgressHUD'
  pod 'OTKAnalytics'
end

target 'OneToOneSampleTests' do 
  pod 'Kiwi'
end