//
//  TextChatComponentChatView.h
//  TextChatComponent
//
//  Created by Xi Huang on 2/23/16.
//  Copyright © 2016 Tokbox. All rights reserved.
//

#import <TextChatKit/TextChatUICustomizator.h>
#import <TextChatKit/TextChat.h>

/**
 *  TextChatViewEventSignal is the enum for signal generated by the textchat
 */
typedef NS_ENUM(NSUInteger, TextChatViewEventSignal) {
    /**
     *  When the component sends a message
     */
    TextChatViewEventSignalDidSendMessage = 0,
    /**
     *  When the component receive a new message
     */
    TextChatViewEventSignalDidReceiveMessage,
    /**
     *  When a new connection is requested and the connection performed successfully
     */
    TextChatViewEventSignalDidConnect,
    /**
     *  When a disconnection is requested and if performed successfully
     */
    TextChatViewEventSignalDidDisconnect
};

/**
 *  TextChatViewEventBlock type for TextChatViewEventSignal different signals
 *
 *  @param signal   NS_ENUM of the signals availables
 *  @param textChat current message send/received
 *  @param error The text chat view object informing something is wrong sending a signal
 */
typedef void (^TextChatViewEventBlock)(TextChatViewEventSignal signal, TextChat *textChat, NSError *error);

@class TextChatView;

/**
 *  The delegate of a TextChatView object must adopt the TextChatViewDelegate protocol. 
 *  Optional methods of the protocol allow the delegate to notify the connectivity.
 */
@protocol TextChatViewDelegate <NSObject>


/**
 *  Tells the delegate the text chat view finishes sending message with or without error
 *  
 *  @param textChatView The text chat view object informing the delegate of this impending event.
 *  @param textChat this is the message object
 *  @param error An error object that text chat view is going to use when encountering an issue
 */
- (void)textChatView:(TextChatView *)textChatView
     didSendtextChat:(TextChat *)textChat
               error:(NSError *)error;

/**
 *  Tells the delegate the text chat view finishes sending message with or without error
 *
 *  @param textChat this is the message object
 *  @param textChatView The text chat view object informing the delegate of this impending event.
 */
- (void)textChatView:(TextChatView *)textChatView
  didReceiveTextChat:(TextChat *)textChat;

@optional

/**
 *  Tells the delegate the text chat view has established a text chat connection with or without error
 *
 *  @param error The text chat view object informing the delegate of this impending event.
 */
- (void)didConnectWithError:(NSError *)error;

/**
 *  Tells the delegate the text chat view has stopped a text chat connection with or without error
 *
 *  @param error The text chat view object informing the delegate of this impending event.
 */
- (void)didDisConnectWithError:(NSError *)error;
@end

@interface TextChatView : UIView

/**
 *  Add the configuration detail to your app.
 *
 *  @param apiKey   Your OpenTok API key.
 *  @param sessionId    The session ID of this instance.
 *  @param token    The token generated for this connection.
 */
+ (void)setOpenTokApiKey:(NSString *)apiKey
               sessionId:(NSString *)sessionId
                   token:(NSString *)token;

/**
 *  The object that acts as the delegate of the text chat view.
 *
 *  The delegate must adopt the TextChatViewDelegate protocol. The delegate is not retained.
 */
@property (weak, nonatomic) id<TextChatViewDelegate> delegate;

/**
 *  A boolean value that indicates whether the text chat view is shown or hidden
 */
@property (readonly, nonatomic, getter=isShown) BOOL show;

/**
 *  The object that manages changeable users interfaces
 */
@property (readonly, nonatomic) TextChatUICustomizator *customizator;

/**
 *  @return Returns an initialized text chat view object
 */
+ (instancetype)textChatView;

/**
 *  Returns an initialized text chat view object whose bottom attached to a given
 *
 *  @param bottomView This is the view the TextChat view is going to attach on top
 *
 *  @return Returns an initialized text chat view object
 */
+ (instancetype)textChatViewWithBottomView:(UIView *)bottomView;

/**
 *  Establishes a text chat connection
 */
- (void)connect;

/**
 *  Establishes a text chat connection with completion
 *
 *  @param handler NS_ENUM for the different event signals
 */
- (void)connectWithHandler:(TextChatViewEventBlock)handler;

/**
 *  Stops a text chat connection
 */
- (void)disconnect;

/**
 *  Shows the text chat view
 */
- (void)show;

/**
 *  Hides the text chat view
 */
- (void)dismiss;

/**
 *  Assign an alias name to the sender
 *
 *  @param alias String with the alias of the sender
 */
- (void)setAlias:(NSString *)alias;

/**
 *  Assign a maximum length of characters each message contains
 *
 *  @param length max number of characters allowed by message
 */
- (void)setMaximumTextMessageLength:(NSUInteger)length;

@end